%Tobias Hör 13.04.03 
%Vers.1.0 beinhaltet das Auswahlfenster mit den Sliders und Buttons
%Vers.1.1: 15.04.03 Die Möglichkeit der Titeleingabe ist neu hinzugekommen
%Vers.1.2: 17.04.03 Verschiedene Fehlfunktionen bei Variablen updates sind korrigiert
%Vers.1.3: 20.04.03 vorläufige Endversion
%Vers.1.4: 23.04.03 Slider und Textbox für das gleitende µ sind dazu gekommen
%Dieses mFile stellt ein Auswahlfenster dar, auf dem verschiedene Variablen mit Hilfe
%von Slidern und Auswahlboxen eingestellt eingestellt werden können.
%Das mFile wird von start1.m aufgerufen und selber ruft es start2.m auf, wenn der 
%"Start"-Button gedrückt wird.

%Generierung des Fensters**********************************************************
h0 = figure('Color',[0.1 0.1 0.1], ...
   'FileName','C:\MATLABR11\Diplom\button.m', ...
   'Name','Auswahlfenster',...
	'NumberTitle','off', ...
	'PaperPosition',[10 180 376 132], ...
	'PaperUnits','points', ...
	'Position',[10 40 427 565],...
   'Tag','Auswahlfenster', ...
   'NumberTitle','off',...
   'MenuBar','none',...
	'ToolBar','none');
%Start Button***********************************************************************
h11 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.6 0.2], ...
	'Callback','start2;', ...
	'ListboxTop',0, ...
	'Position',[10 10 45 15], ...
	'String','Start', ...
   'Tag','Start');
%Checkbox ob Figure6 die 3D Ansicht der Koeffizienten darstellen soll***************
h12 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.1 0.1 0.1], ...
   'Callback',...
   'DREID=get(h12,''Value'');', ...
	'ListboxTop',0, ...
	'Position',[105 55 45 15], ...
	'Style','checkbox', ...
   'Tag','3D');
%Slider zum einstellen der Störfrequenz*********************************************
h13 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'ListboxTop',0, ...
	'Max',10000, ...
   'Min',0, ...
   'SliderStep',[0.0001 0.001], ...
	'Position',[72 160 45 15], ...
	'Style','slider', ...
   'Tag','Störfrequenz', ...
   'CallBack', ...
   ['FREQUENZST=get(h13,''value'');',...
   'set(texval1,''String'',num2str(FREQUENZST))'],...
	'Value',1000);
%Textfeld zeigt den aktuellen Wert der Störfrequenz an*******************************
texval1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.2 0.2], ...
	'ListboxTop',0, ...
   'SliderStep',[0.0001 0.001], ...
	'Position',[24 160 45 15], ...
	'String','1000', ...
	'Style','text', ...
	'Tag','Zahl Störfrequenz');
%Slider zum einstellen der Abtastfrequenz********************************************
h14 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'ListboxTop',0, ...
	'Max',24000, ...
   'Min',0, ...
   'SliderStep',[0.0001 0.001], ...
	'Position',[72 185 45 15], ...
	'Style','slider', ...
   'Tag','Abtastfrequenz', ...
   'CallBack', ...
   ['ABTASTFR=get(h14,''value'');',...
   'ABTASTFR=round(ABTASTFR);',...
   'set(h14,''Value'',ABTASTFR);',...
   'set(texval2,''String'',num2str(ABTASTFR))'],...
	'Value',8000);
%Textfeld zeigt den aktuellen Wert der Abtastfrequenz an******************************
texval2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.2 0.2], ...
	'ListboxTop',0, ...
	'Position',[24 185 45 15], ...
	'String','8000', ...
	'Style','text', ...
	'Tag','Zahl Abtastfrequenz');
%Slider zum auswählen des MUE**********************************************************
h15 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'ListboxTop',0, ...
	'Max',1, ...
   'Min',0, ...
   'SliderStep',[0.0001 0.01], ...
	'Position',[72 210 45 15], ...
	'Style','slider', ...
   'Tag','Mue', ...
   'CallBack', ...
   ['MUE=get(h15,''value'');',...
   'set(texval3,''String'',num2str(MUE));',...
   'if MUE==1;',...
   '	MUE=32767;',...
	'else;',...
   '	MUE=round(MUE*2^15);',...
	'end;'],...
	'Value',0.003);
%Textfeld zeigt den aktuellen WErt des MUE**********************************************
texval3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.2 0.2], ...
	'ListboxTop',0, ...
	'Position',[24 210 45 15], ...
	'String','0.003', ...
	'Style','text', ...
	'Tag','Zahl des MUE');

%Slider zum einstellen der Frequenz des erwünschten Signals*****************************
h16 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'ListboxTop',0, ...
	'Max',10000, ...
   'Min',0, ...
   'SliderStep',[0.0001 0.001], ...
	'Position',[72 135 45 15], ...
	'Style','slider', ...
   'Tag','Frequenz erw. Signal', ...
   'CallBack', ...
   ['FREQUENZERW=get(h16,''value'');',...
   'set(texval4,''String'',num2str(FREQUENZERW))'],...
	'Value',500);
%Textfeld zeigt den aktuellen Wert der Frequenz des erwünschten Signals*****************
texval4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.2 0.2], ...
	'ListboxTop',0, ...
	'Position',[24 135 45 15], ...
	'String','500', ...
	'Style','text', ...
	'Tag','Zahl Frequenz erw Signal');
%Slider zum einstellen der Amplituden****************************************************
h17 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'ListboxTop',0, ...
   'Min',0, ...
   'SliderStep',[0.001 0.01], ...
	'Position',[72 85 45 15], ...
	'Style','slider', ...
   'Tag','Amplitude', ...
   'CallBack', ...
   ['AMPLITUDE=get(h17,''value'');',...
   'set(texval5,''String'',num2str(AMPLITUDE))'],...
	'Value',0.5);
%Textfeld zeigt den aktuellen Wert der Amplitude******************************************
texval5 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.2 0.2], ...
	'ListboxTop',0, ...
	'Position',[24 85 45 15], ...
	'String','0.5 ', ...
	'Style','text', ...
   'Tag','Zahl Amplitude');
%Auswahlbox zum Einstellen der SAMPLES****************************************************
h18 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.925490196078431 0.913725490196078 0.847058823529412], ...
   'Callback',...
   ['clear SAMPLES;',...
   'SAMPLES=get(h18,''Value'');',...
   'if SAMPLES==1;',...
   '	SAMPLES=256;'...
	'elseif SAMPLES==2;',...	
   '	SAMPLES=512;',...
	'elseif SAMPLES==3;',...	
   '	SAMPLES=1024;',...
	'elseif SAMPLES==4;',...	
   '	SAMPLES=2048;',...
	'elseif SAMPLES==5;',...	
   '	SAMPLES=4096;',...
   'end;'],...
	'ListboxTop',0, ...
	'Position',[72 235 45 15], ...
	'String',[' 256';'512 ';'1024';'2048';'4096'], ...
	'Style','popupmenu', ...
	'Tag','Samples', ...
   'Value',1);
%Textfeld für den Titel des Fensters********************************************************
	 uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.4 0.8 0.4], ...
	'ListboxTop',0, ...
	'Position',[0.75 400 318 21.75], ...
   'String',['Tobias Hör Vers.1.4',...
   '                                                                             ',...
   '                               ',...
   'Alle hier angezeigten Kommawerte werden intern in das Integer Format',...
   ' umgerechnet!'], ...
	'Style','text', ...
   'Tag','StaticText1');
%Textfeld für die Samples Auswahl***********************************************************
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 235 96 15], ...
	'String','Auswahl der Samples', ...
	'Style','text', ...
   'Tag','StaticText2');
%Textfeld Auswahl des µ*********************************************************************
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 210 90 15], ...
	'String','Auswahl des µ', ...
	'Style','text', ...
   'Tag','StaticText3');
%Textfeld Abtastfrequenz********************************************************************
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 185 90.75 15], ...
	'String','Abtastfrequenz ', ...
	'Style','text', ...
   'Tag','StaticText4');
%Textfeld Störfrequenz***********************************************************************
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 160 45 15], ...
	'String','Störfrequenz', ...
	'Style','text', ...
   'Tag','StaticText5');
%Textfeld Frequenz des erwünschten Signals***************************************************
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 135 132 15], ...
	'String','Frequenz des erwünschten Signals', ...
	'Style','text', ...
   'Tag','StaticText6');
%Textfeld Amplitude**************************************************************************
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 85 46.5 15], ...
	'String','Amplitude ', ...
	'Style','text', ...
   'Tag','StaticText7');
%Textfeld für die Checkbox der 3D Ansicht der Koeffizienten**********************************
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 50 101.25 30], ...
	'String','Soll für die Koeffizienten die 3D Ansicht ausgegeben werden?', ...
	'Style','text', ...
   'Tag','StaticText8');
%Slider zum einstellen der Filterordnung******************************************************
h29 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'ListboxTop',0, ...
	'Max',499, ...
   'Min',11, ...
   'SliderStep',[0.005 0.01], ...
	'Position',[72 110 45 15], ...
	'Style','slider', ...
   'Tag','Filterordnung', ...
   'CallBack', ...
   ['clear ORDNUNG;',...
   'ORDNUNG=get(h29,''value'');',...
   'ORDNUNG=round(ORDNUNG);',...   
   'set(h29,''value'',ORDNUNG);',...
   'set(texval6,''String'',num2str(ORDNUNG))'],...
	'Value',21);
%Textfeld zum Anzeigen des aktuellen Wertes der Filterordnung**********************************
texval6 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.2 0.2], ...
	'ListboxTop',0, ...
	'Position',[24 110 45 15], ...
	'String','21', ...
	'Style','text', ...
	'Tag','StaticText10');
%Textfeld Filterordnung************************************************************************
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 110 56.25 15], ...
	'String','Filterordnung', ...
	'Style','text', ...
   'Tag','StaticText10');
%Nun kommt die Titeleingabe und Ihre Textfelder************************************************
h31 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[21 380 165 15], ...
   'Style','edit', ...
   'CallBack', ...
   ['TIT=1;','Fig2;'],...
	'Tag','Edit Titel Figure2');
	uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[188 380 45 15], ...
	'String','Titel Figure2', ...
	'Style','text', ...
	'Tag','StaticText11');
h34 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','TIT=1;Fig3;', ...
	'ListboxTop',0, ...
	'Position',[21 360 165 15], ...
	'Style','edit', ...
	'Tag','Titel Fig3');
h35 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','TIT=1;Fig4;', ...
	'ListboxTop',0, ...
	'Position',[21 340 165 15], ...
	'Style','edit',... 
	'Tag','Titel Fig4');
h36 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','TIT=1;Fig5;', ...
	'ListboxTop',0, ...
	'Position',[21 320 165 15], ...
	'Style','edit', ...
	'Tag','Titel Fig5');
h37 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','TIT=1;Fig6;', ...
	'ListboxTop',0, ...
	'Position',[21 300 165 15], ...
	'Style','edit', ...
	'Tag','Titel Fig6');
h38 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','TIT=1;Fig7;', ...
	'ListboxTop',0, ...
	'Position',[21 280 165 15], ...
	'Style','edit', ...
	'Tag','Titel Fig7');
h39 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','TIT=1;Fig8;', ...
	'ListboxTop',0, ...
	'Position',[21 260 165 15], ...
	'Style','edit', ...
	'Tag','Titel Fig8');
h40 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[188 360 45 15], ...
	'String','Titel Figure3', ...
	'Style','text', ...
	'Tag','StaticText12');
h41 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[188 340 45 15], ...
	'String','Titel Figure4', ...
	'Style','text', ...
	'Tag','StaticText13');
h42 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[188 320 45 15], ...
	'String','Titel Figure5', ...
	'Style','text', ...
	'Tag','StaticText14');
h43 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[188 300 45 15], ...
	'String','Titel Figure6', ...
	'Style','text', ...
	'Tag','StaticText15');
h44 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[188 280 45 15], ...
	'String','Titel Figure7', ...
	'Style','text', ...
	'Tag','StaticText16');
h45 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[188 260 45 15], ...
	'String','Titel Figure8', ...
	'Style','text', ...
   'Tag','StaticText17');
%Ende Button beendet gesamtes Programm
h46 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.5 0.6], ...
   'Callback',['clear all;','close all;'], ...
	'ListboxTop',0, ...
	'Position',[255.75 11.25 45 15], ...
	'String','Ende', ...
   'Tag','Pushbutton1');
%Checkbox zur verwendung des gleitenden MUE's
h47 = uicontrol('Parent',h0, ...
	'Units','points', ...
 	'BackgroundColor',[0.1 0.1 0.1], ...
	'ListboxTop',0, ...
   'Callback',...
   ['GLEITEN=get(h47,''Value'');', ...
   'if GLEITEN ==0;',...
   '	MUE=get(h15,''value'');',...
   '	MUE=round(MUE*2^15);',...
   'end;'],...
	'Position',[105 25.5 15 15], ...
	'Style','checkbox', ...
   'Tag','Gleitendes µ');
%Textfeld zur Checkbox
uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.9], ...
	'ListboxTop',0, ...
	'Position',[126 22.5 100.5 22.5], ...
	'String','Soll ein gleitendes µ verwendet werden?', ...
	'Style','text', ...
	'Tag','StaticText9');


