% program to open user interface for digital communications lab exercise 
%
% Hamburg University of Applied Sciences  
% Department of Informations- und Elektrotechnik
%
% Author: Prof. Dr.-Ing. Hans J. Micheel
% Author: Prof. Dr.-Ing. Rainer Schoenen
% Date: 10.03.2009
% Date: 20.03.2015

global c;
if (c.init_done~=true)
    % init file not loaded
    fprintf('Warning: init_digital_communications was not called before !\n');
    init_digital_communications;
end
% Variables
A='STP1';
B='STP2';	% nur 4 Ziffern verwenden
C='STP3';
D='STP4';
E='METO';
F='SYST';
%G='UZZ';
H='Help';

figure(102), clf

% image(imread('icon.tif'))			% read image
[X,map] = imread('icon.tif');
if ~isempty(map)
    Im = ind2rgb(X,map);
end
%whos Im
image(Im)			% read image
axis off			% no axis


%define buttons to open tool boxes

STP1_call = uicontrol(gcf, 'style', 'push',...
											'position', [110 330 150 30],...
                                 'string', 'project step 1',...
                                 'TooltipString','opens library',...
                                 'callback', 'block_due(A)');                                                                                                                   
                                    
STP2_call  = uicontrol(gcf, 'style', 'push',...
											'position', [170 275 150 30],...
                                 'string', 'project step 2',...
                                 'TooltipString','opens library',...
                                 'callback', 'block_due(B)');                                  
                                                      
STP3_call = uicontrol(gcf, 'style', 'push',...
											'position', [230 220 150 30],...
                                 'string', 'project step 3',...
                                 'TooltipString','opens library',...
                                 'callback', 'block_due(C)');  
                                    
STP4_call = uicontrol(gcf, 'style', 'push',...
											'position', [290 165 150 30],...
                                 'string', 'project step 4',...
                                 'TooltipString','opens library',...
                                 'callback', 'block_due(D)');                                                               

METO_call = uicontrol(gcf, 'style', 'push',...
											'position', [440 265 150 40],...
                                 'string', 'Measurement Tools',...
                                 'TooltipString','opens toolbox',...
                                 'callback', 'block_due(E)');
                             
SYST_call = uicontrol(gcf, 'style', 'push',...
											'position', [440 330 150 40],...
                                 'string', 'System Blocks',...
                                 'TooltipString','opens toolbox',...
                                 'callback', 'block_due(F)');
                              
                              
Help_call = uicontrol(gcf, 'style', 'push',...
											'position', [200 10 150 30],...
                                 'string', 'Help',...
                                 'TooltipString','hint for help',...
                                 'callback', 'block_due(H)');
                                    
                                                               
Close_call = uicontrol(gcf, 'style', 'push',...
											'position', [440 10 150 30],...
                                 'string', 'close',...
                                 'TooltipString','Close window',...   
	                              'callback', 'close');
                                    
                           
                                    
%define buttons to plot measurement results                                
                                    
plot1_call = uicontrol(gcf, 'style', 'push',...
											'position', [110 95 150 40],...
                                 'string', 'plot signal prop.',...
                                 'TooltipString','opens plot menu',...
                                 'callback', 'shows_due');
                                    


%Texte                                     
Version = uicontrol(gcf, 'style', 'text',...   
   										'position', [0 395 591 20],...
                                 'string', ' Project "Digital Communication Systems"');             
                                    
copyright = uicontrol(gcf, 'style', 'text',...
											'position', [15 0 15 460],...
                                 'string', 'C');  
                                    
text(180,142,'Prof. Dr.-Ing. Micheel/Kröger/Schoenen')